# Generated by Django 5.2.10 on 2026-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAELabourContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('establishment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_representative', models.CharField(blank=True, max_length=200, null=True)),
                ('emirate', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('work_style', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_issue_date', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_passport_no', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('work_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('weekly_rest', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_leave', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_date', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
