# Generated by Django 5.2.10 on 2026-03-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0003_uaedocumentemiratesid_uaedocumentpassport'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentemiratesid',
            name='family_sponsor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
