# Generated by Django 5.2.10 on 2026-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0004_uaedocumentemiratesid_family_sponsor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='id_number',
            new_name='emirates_id',
        ),
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='employer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='permit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
