# Generated by Django 5.2.10 on 2026-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0005_rename_id_number_uaedocumentvisa_emirates_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEMedicalApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('application_date', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('height_cm', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=20, null=True)),
                ('uae_resident', models.CharField(blank=True, max_length=10, null=True)),
                ('already_insured', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_declined', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_substandard', models.CharField(blank=True, max_length=10, null=True)),
                ('hazardous_sports', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_answers', models.JSONField(blank=True, null=True)),
                ('pregnancy', models.JSONField(blank=True, null=True)),
                ('cancer_section', models.JSONField(blank=True, null=True)),
                ('dental_problems', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
