# Generated by Django 5.2.10 on 2026-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0006_uaemedicalapplicationform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='plan',
            new_name='application_policy_no',
        ),
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='insurance_substandard',
            new_name='blood_disorders',
        ),
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='address',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='applicant_name',
            new_name='insured_name',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='cancer_section',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='medical_answers',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='pregnancy',
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='active_at_work_since',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_chemotherapy_cycles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_radiation_cycles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_radiotherapy_cycles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cancer_surgery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='cardiovascular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='chronic_disease',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='congenital',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='dental_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='dental_last_treatment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='digestive_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='endocrine_diseases',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='family_cancer_history',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='fertility_treatment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='genitourinary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='good_health',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='has_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='hazardous_sports_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='infectious_diseases',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='injury_poisoning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='insurance_substandard_terms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='insured_since',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='last_menstrual_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='maternity_history',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='mental_disorders',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='musculoskeletal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='nervous_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='organ_surgery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='perinatal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='pre_existing_disease',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='pregnancy_complications',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='pregnant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='previous_hospitalization',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='required_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='respiratory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='smoking_alcohol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='trying_to_conceive',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='weight_change',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uaemedicalapplicationform',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
