# Generated by Django 5.2.10 on 2026-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0007_rename_plan_uaemedicalapplicationform_application_policy_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentEVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('uid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('issuing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UAEDocumentResidenceVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('uid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('issuing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
