# Generated by Django 5.2.10 on 2026-03-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0008_uaedocumentevisa_uaedocumentresidencevisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaedocumentevisa',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='uaedocumentresidencevisa',
            name='uid_no',
        ),
    ]
