# Generated by Django 5.2.10 on 2026-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0009_remove_uaedocumentevisa_expiry_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UAEDocumentEVisa',
        ),
        migrations.DeleteModel(
            name='UAEDocumentResidenceVisa',
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='family_sponsor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
