# Generated by Django 5.2.10 on 2026-03-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0010_delete_uaedocumentevisa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='employer_name',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='family_sponsor_name',
            new_name='sponsor_name',
        ),
    ]
