# Generated by Django 5.2.12 on 2026-04-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0011_rename_employer_name_uaedocumentvisa_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaelabourcontract',
            name='total_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
