# Generated by Django 5.2.12 on 2026-04-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0012_uaelabourcontract_total_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='cancer',
            new_name='general_cancer_question',
        ),
    ]
