# Generated by Django 5.2.12 on 2026-04-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0013_rename_cancer_uaemedicalapplicationform_general_cancer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='hazardous_sports',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='hazardous_sports_details',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='insurance_declined',
        ),
        migrations.RemoveField(
            model_name='uaemedicalapplicationform',
            name='insurance_substandard_terms',
        ),
    ]
