# Generated by Django 5.2.12 on 2026-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0014_remove_uaemedicalapplicationform_hazardous_sports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaemedicalapplicationform',
            old_name='general_cancer_question',
            new_name='cancer',
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='hazardous_sports',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='hazardous_sports_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='insurance_declined',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='insurance_substandard_terms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
