# Generated by Django 5.2.12 on 2026-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0015_rename_general_cancer_question_uaemedicalapplicationform_cancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='Hepatitis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='Shortness_vision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uaemedicalapplicationform',
            name='bone_fractures',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
