# Generated by Django 5.2.12 on 2026-04-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0016_uaemedicalapplicationform_hepatitis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='stamp_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='stamp_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
