# Generated by Django 5.2.12 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0017_uaedocumentpassport_stamp_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentCOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_name', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('inception_date', models.CharField(blank=True, max_length=50, null=True)),
                ('insured_until', models.CharField(blank=True, max_length=50, null=True)),
                ('coc_reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('coc_validity_date', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=50, null=True)),
                ('insurer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UAEDocumentResidenceCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=50, null=True)),
                ('residence_no', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('cancel_date', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
