# Generated by Django 5.2.12 on 2026-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0018_uaedocumentcoc_uaedocumentresidencecancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentcoc',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentcoc',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
