# Generated by Django 5.2.12 on 2026-04-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0019_uaedocumentcoc_date_of_birth_uaedocumentcoc_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentcoc',
            name='policy_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
