# Generated by Django 5.2.12 on 2026-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0020_uaedocumentcoc_policy_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='from_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='port_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='to_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentpassport',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='from_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='port_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='to_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
