# Generated by Django 5.2.12 on 2026-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0021_uaedocumentpassport_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentTravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.CharField(blank=True, max_length=50, null=True)),
                ('to_date', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('port_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
