# Generated by Django 5.2.12 on 2026-05-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0022_uaedocumenttravelhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentBusinessLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registry_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unified_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customs_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_form', models.CharField(blank=True, max_length=200, null=True)),
                ('licence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('licence_category', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('issuance_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_up_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_up_capital_in_words', models.TextField(blank=True, null=True)),
                ('adcci_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mohre_establishment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('icp_establishment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_role', models.CharField(blank=True, max_length=100, null=True)),
                ('share_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('official_email', models.CharField(blank=True, max_length=200, null=True)),
                ('official_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, null=True)),
                ('activity_code', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
