# Generated by Django 5.2.12 on 2026-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0023_uaedocumentbusinesslicence'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaedocumentemiratesid',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
