# Generated by Django 5.2.10 on 2026-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tests', '0024_uaedocumentemiratesid_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentTOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='TOB', max_length=50)),
                ('matched_keywords', models.TextField(blank=True, null=True)),
                ('signature_present', models.BooleanField(default=False)),
                ('signature_pages', models.TextField(blank=True, null=True)),
                ('signature_locations', models.TextField(blank=True, null=True)),
                ('signature_status', models.CharField(blank=True, max_length=50, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
