# Generated by Django 5.2.10 on 2026-01-28 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_rename_employer_sponsor_name_insuranceapplication_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='has_medical_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='maf_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='passports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='visas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
