# Generated by Django 5.2.10 on 2026-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insuranceapplication_has_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapplication',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('<4000', 'Below 4000 AED'), ('4000-5000', '4000-5000 AED'), ('>5000', 'Above 5000 AED')], max_length=20, null=True),
        ),
    ]
