# Generated by Django 5.2.10 on 2026-02-06 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insuranceapplication_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='uid_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('NEW', 'New Entrant'), ('TRANSFER', 'Transferred from Other Emirates'), ('EXISTING_AD', 'Existing Abu Dhabi Visa Holder'), ('NEWBORN', 'Newborn')], max_length=20, null=True),
        ),
    ]
