# Generated by Django 5.2.10 on 2026-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insuranceapplication_uid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_status_date',
            field=models.DateField(blank=True, help_text='Entry Date, Last Expiry Date, or Date of Birth based on Visa Type', null=True),
        ),
    ]
