# Generated by Django 5.2.10 on 2026-02-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_insuranceapplication_visa_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='passport_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_eid_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='visa_passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
